version: "3.1"
services:
  db:
    image: postgres
    restart: always
    container_name: postgres
    environment:
      POSTGRES_USER: mateus
      POSTGRES_PASSWORD: postgres
    ports:
      - "3306:3307"
    volumes:
      - devdojo_new_data:/var/lib/mysql

volumes:
  devdojo_new_data: